---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: binding1
  namespace: rabbitmq-system3
spec:
  vhost: "vhost1"
  source: fanout1
  destination: qq1
  destinationType: queue
  rabbitmqClusterReference:
    name: rabbit1
