---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: binding3
  namespace: rabbitmq-system5
spec:
  vhost: "vhost3"
  source: fanout3
  destination: qq3
  destinationType: queue
  rabbitmqClusterReference:
    name: rabbit1
