---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: downstream-queue
  namespace: rabbitmq-system5
spec:
  name: downstream-queue
  vhost: "downstream"
  type: quorum
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbit2
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: upstream-queue
  namespace: rabbitmq-system5
spec:
  name: upstream-queue
  vhost: "upstream"
  type: quorum
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbit2
