---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: upstream-vhost
  namespace: rabbitmq-system3
spec:
  name: upstream
  rabbitmqClusterReference:
    name: rabbit2
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: downstream-vhost
  namespace: rabbitmq-system3
spec:
  name: downstream
  rabbitmqClusterReference:
    name: rabbit2
